export const redemptionSummary = [{
	id: 'SHOT_OR_WATER',
	icon: 'https://d3e4ixgvd0ibii.cloudfront.net/shopify/icons/pressed-points/water-and-shot.svg',
	title: 'Shot or Water',
	points: 70,
	eligibleCartItemQuantity: 1,
	requestedRedemptionQuantity: 0,
}, {
	id: 'FREEZE_SIZE_1',
	icon: 'https://d3e4ixgvd0ibii.cloudfront.net/shopify/icons/pressed-points/freeze-size-1.svg',
	title: 'Size 1 Freeze',
	points: 140,
	eligibleCartItemQuantity: 1,
	requestedRedemptionQuantity: 0,
}, {
	id: 'JUICE',
	icon: 'https://d3e4ixgvd0ibii.cloudfront.net/shopify/icons/pressed-points/juice.svg',
	title: 'Any Juice',
	points: 150,
	eligibleCartItemQuantity: 1,
	requestedRedemptionQuantity: 0,
}, {
	id: 'SIGNATURE_BLEND',
	icon: 'https://d3e4ixgvd0ibii.cloudfront.net/shopify/icons/pressed-points/signature-blend.svg',
	title: 'Signature Blend',
	points: 180,
	eligibleCartItemQuantity: 1,
	requestedRedemptionQuantity: 0,
}, {
	id: 'FREEZE_SIZE_2',
	icon: 'https://d3e4ixgvd0ibii.cloudfront.net/shopify/icons/pressed-points/freeze-size-2.svg',
	title: 'Size 2 Freeze',
	points: 180,
	eligibleCartItemQuantity: 1,
	requestedRedemptionQuantity: 0,
}];
