version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - run:
          name: Update NPM
          command: sudo npm install -g npm@latest
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run lint
          command: npm run lint
      - run:
          name: Compile and serve Storybook
          command: npm start
          background: true
      - run:
          name: Wait until server is live
          command: |
                  wget --retry-connrefused --waitretry=1 --timeout=10 --tries 60 --spider http://localhost:6006
                  :
      - run:
          name: Take screenshots
          command: npm run snapshots
      - run:
          name: Kill Storybook
          command: pkill -f storybook
